=== meiyy0710/midterm-activity_Nakagawa/store.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="https://www.example.com"
  xmlns="https://www.example.com"
  elementFormDefault="qualified">

  <xs:element name="store">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="barcode" type="xs:string"/>
        <xs:element name="brand" type="xs:string"/>
        <xs:element name="category" type="xs:string"/>
        <xs:element name="currency" type="xs:string"/>
        <xs:element name="expirationDate" type="xs:string"/>
        <xs:element name="name" type="xs:string"/>
        <xs:element name="price" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

</xs:schema>

=== meiyy0710/midterm-activity_Nakagawa/store.xml
<?xml version="1.0"?>
<store xmlns="https://www.example.com"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="https://www.example.com store.xsd">

  <barcode>4800092116537</barcode>
  <brand>Choco Mucho</brand>
  <category>Snacks</category>
  <currency>PHP</currency>
  <expirationDate>2026-07-20</expirationDate>
  <name>Choco bar</name>
  <price>35.00</price>
  
</store>
